name: note_app
description: Note App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dartz: ^0.10.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  path: ^1.8.3
  sqflite: ^2.3.0
  state_notifier: ^1.0.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
